Homework
Graffiland/github_practice_2023_2 pull request #1
Opened 2023-05-04 18:34 UTC by ivombi

This PR contains the following changes

1. I created questions
2. Assign those questions to students

2023-05-04 18:43 UTC, BihBerniceF requested changes
Please can you add the line 'practice session'?

2023-05-04 18:45 UTC, ivombi commented
> Please can you add the line 'practice session'?

@BihBerniceF I think removing make sense.

2023-05-04 18:49 UTC, BihBerniceF approved these changes
Good to merge

2023-05-04 18:50 UTC, merged

2023-05-11 00:40 UTC, Erastusndi reviewed
nice one mate. crack on and merge.

2023-05-11 08:14 UTC, tyanko55 commented on README.md
> +
it is a source which allows you merge feature ideas  in a contained area of repository .